### ISSUE TITLE
Installation via pip fails

### ISSUE THREAD

**Issue by h-rueda** [nabla-c0d3/sslyze#306]
I am not sure whether this is a **sslyze** or a python packaging issue.
When I try to install/update **sslyze** I get a dependency error message

`sudo pip install --upgrade sslyze
Collecting sslyze
  Using cached SSLyze-1.4.1.tar.gz
Collecting nassl<1.2.0,>=1.1.0 (from sslyze)
  Could not find a version that satisfies the requirement nassl<1.2.0,>=1.1.0 (from sslyze) (from versions: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3)
No matching distribution found for nassl<1.2.0,>=1.1.0 (from sslyze)
`

**Comment by vdeturckheim** [comment]
I had the same issue and ended up using `pip install sslyze==1.3.4`

**Comment by nottheend** [comment]
It works fine with Python 3.6

**Comment by nabla-c0d3** [comment]
Something is wrong with the nassl Linux wheel for 2.7. If possible you should switch to python 3.6.

**Comment by konklone** [comment]
I observed (on a coworker's computer) this exact error message happening on native OS X, under Python 3.5. 

Installing SSLyze 1.3.4 solved the issue (for the time being) for this person, but I think it may not just be a Linux/2.7 issue.

**Comment by nabla-c0d3** [comment]
I fixed the Linux wheel for Python 2.7 (https://travis-ci.org/nabla-c0d3/sslyze/jobs/363564491) so it should now work fine if you get the latest nassl.

On macOS I've only built a Python 3.6 wheel hence your error.

**Comment by zarquon5** [comment]
For the record, the version for Windows/Python 2.7 is still broken.

**Comment by wsargent** [comment]
Same problem on OS X:

❱ pip install --upgrade sslyze

Collecting sslyze
  Using cached https://files.pythonhosted.org/packages/73/a6/424284342a49c1be7669c7620de53fa736b6b0785dd07a6edcf0008d8ef0/SSLyze-1.4.2.tar.gz
Collecting nassl<1.2.0,>=1.1.0 (from sslyze)
  Could not find a version that satisfies the requirement nassl<1.2.0,>=1.1.0 (from sslyze) (from versions: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3)
No matching distribution found for nassl<1.2.0,>=1.1.0 (from sslyze)

**Comment by nabla-c0d3** [comment]
It works for me on MacOS on both Python 2.7 and Python 3.6.

**Comment by regenscheid** [comment]
@nabla-c0d3 -
I've got the same problem as @wsargent when trying to install via pip/pip3 in Mac OS 10.12.  I get the same error message whether I'm using brew-installed Python 2.7.15 or working in a Python 3.7.0 virtualenv.

For what it's worth, I can install via brew, but then I run into the certinfo errors described in #320. I've been trying to find some sort of fix.
